export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as Blog } from './Blog'
export { default as Team } from './Team'
export { default as Careers } from './Careers'
export { default as Footer } from './Footer'
export { default as SinglePost } from './SinglePost'